server:
  port: 8081
  servlet:
    context-path: /api/v1
spring:
  application:
    name: workloads-service
  data:
    mongodb:
      host: ${MONGO_HOST:host.docker.internal}
      port: 27017
      database: workload
  activemq:
    broker-url: tcp://${MQ_HOST:host.docker.internal}:61616
    user: ${MQ_USER:admin}
    password: ${MQ_PASSWORD:admin}
    packages:
      trust-all: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
jwt:
  secret: ${JWT_KEY}